# Generated by Django 5.0.6 on 2024-07-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maltron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='productos/'),
        ),
    ]
