# Generated by Django 5.0.6 on 2024-07-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maltron', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='informacion',
            field=models.CharField(max_length=10000),
        ),
    ]
