# Generated by Django 5.0.6 on 2024-07-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maltron', '0003_alter_producto_informacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
